### ISSUE TITLE
link for final dataset

### ISSUE THREAD

**Issue by betterze** [Tin-Kramberger/LSUN-Stanford-dataset#1]
Dear Tin-Kramberger,

Thank you for your great work, I really like it.

Would you mind share a link to download the final dataset? Lsun car is too big (170G), I can not even download it. If I can download the final and small dataset, it will be very helpful for me.

Thank you very much for your help.

Best Wishes,

Alex

**Comment by Tin-Kramberger** [comment]
Dear Alex,

our dataset has to have initial Stanford and LSUN car dataset downloaded first to work.
It is basically a SQL database which connects the datasets and outputs. With the python code provided here on GitHub you can extract the data that you need for the project as is described in the [readme](https://github.com/Tin-Kramberger/LSUN-Stanford-dataset/blob/master/README.md) file.
I'll upload the dataset and add the link to it during next couple of days.

Best regards,
Tin

**Comment by Tin-Kramberger** [comment]
I have uploaded the dataset on server. You can download it from this link: [LSUN-Stanford-cropped](http://homer.tvz.hr/datasets/LSUN-Stanford-cropped.zip)

**Comment by betterze** [comment]
thx a lot, I will take a lot of it.

**Comment by betterze** [comment]
@Tin-Kramberger Would you mind tell me how many images in the file? Or how large is the file after unzip? My unzip command has run for 5h, I am not sure if something wrong.

**Comment by Tin-Kramberger** [comment]
Well, it depends on your configuration how long would it take to unzip the files. Eg. do you have SSD drive or not.
It says in the Abstract of the paper: Pruning the combined LSUN and Stanford datasets resulted in 2,067,710 images of cars, so there should be exact number of images in the dataset that I have added for you.
I'm not sure about the unpacked size, but my guess would be that it is simmilar to zip file size.

**Comment by betterze** [comment]
Get it, thx a lot.
