### ISSUE TITLE
pretrained model for stylegan2

### ISSUE THREAD

**Issue by betterze** [Tin-Kramberger/LSUN-Stanford-dataset#2]
Dear Tin-Kramberger,

Thnak you for sharing with us this good dataset. 

Do you have pretrained model for StyleGAN2 on your dataset? Would you mind sharing it with us? I try to train it by myself, but it takes too much disk space, I can not even convert the dataset to tfrecord, which is necessary for training StyleGAN.

Thank you for your help. 

Best Wishes,

Alex

**Comment by Tin-Kramberger** [comment]
Dear Alex,

Yes, everything is on the google drive link from the readme including the pretrained network: https://drive.google.com/drive/folders/10L49FrRzlBKyacKNZl4nPdil5JBWBlFh

Best regards,
Tin

**Comment by betterze** [comment]
Dear Tin,

If I understand correctly from your paper (In introduction, the second to last paragraph), the model you trained is StyleGAN1, not StyleGAN2, right? 

But I try to load the model, it seems like it is StyleGAN2, since it contains ToRGB layer. 

Sorry to be annoying, just want to make sure before I use it.

Thank you very much for your help. You are very nice.

Best Wishes,

Alex

**Comment by Tin-Kramberger** [comment]
Dear Alex,

yes, I've trained only the StyleGAN. This one: https://github.com/NVlabs/stylegan

I haven't got any pretrained StyleGAN2 models. StyleGAN2 came out just few days after I've finished my work.

Best regards,
Tin

**Comment by betterze** [comment]
Dear Tin, 

Thank you for your clarificatio. I will try to train it on StyleGAN2.

Thank you for your help.

Best Wishes,

Alex
